// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSltZs0eA_oFa-0DYIYoeLwEWlaIC2xfs',
    appId: '1:694098863062:web:5a10e0fd2b40f3c75bba77',
    messagingSenderId: '694098863062',
    projectId: 'flutter-b1109',
    authDomain: 'flutter-b1109.firebaseapp.com',
    storageBucket: 'flutter-b1109.firebasestorage.app',
    measurementId: 'G-BHLKEP9SSD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdCJ8KzaafZVDf7Wf5zPIgDqGBsvfXUDc',
    appId: '1:694098863062:android:0babe37f9c6589915bba77',
    messagingSenderId: '694098863062',
    projectId: 'flutter-b1109',
    storageBucket: 'flutter-b1109.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWKmIzjxSgIUJP_5u-7VUDSqYUzwyP9FA',
    appId: '1:694098863062:ios:7066c9e722f184005bba77',
    messagingSenderId: '694098863062',
    projectId: 'flutter-b1109',
    storageBucket: 'flutter-b1109.firebasestorage.app',
    iosBundleId: 'com.example.financeManagment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWKmIzjxSgIUJP_5u-7VUDSqYUzwyP9FA',
    appId: '1:694098863062:ios:7066c9e722f184005bba77',
    messagingSenderId: '694098863062',
    projectId: 'flutter-b1109',
    storageBucket: 'flutter-b1109.firebasestorage.app',
    iosBundleId: 'com.example.financeManagment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSltZs0eA_oFa-0DYIYoeLwEWlaIC2xfs',
    appId: '1:694098863062:web:7c622a29dc418add5bba77',
    messagingSenderId: '694098863062',
    projectId: 'flutter-b1109',
    authDomain: 'flutter-b1109.firebaseapp.com',
    storageBucket: 'flutter-b1109.firebasestorage.app',
    measurementId: 'G-NJ09HTLGYE',
  );
}
